# Site settings
layout: default
title: Offer Acceptance in the Freight Industry
description: A project investigating optimal stopping in the freight marketplace.
url: https://radumanea23.github.io/UCSDFlockFreightCapstone

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
