# Site settings
title: Offer Acceptance in the Freight Industry
description: Your site description
url: https://radumanea23.github.io/UCSDFlockFreightCapstone

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
